### ISSUE TITLE
Npm package import errors

### ISSUE THREAD

**Issue by mattrossman** [argonjs/three-web-layer#3]
After installing the latest `three-web-layer` and `ethereal`, I'm getting the following error when importing `WebLayer3D`:

```
./node_modules/ethereal/dist/ethereal.mjs
Can't import the named export 'Box3' from non EcmaScript module (only default export is available)
```

Some other notes:
* The README says to `import WebLayer3D from 'three-web-layer'` but there is no default export, it should be `import { WebLayer3D } from 'three-web-layer'`
* The README doesn't mention the required `ethereal` dependency (not sure what this is tbh)

**Comment by the-reality-engineer** [comment]
Thanks for the notes. I've actually integrated this code into another framework I have been working on (ethereal), which includes a few fixes and performance improvements that aren't in this repository, so this repo is effectively deprecated. Let's talk tomorrow; I'll message you on Teams.
